// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgqvainhgfmfhttendyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncXZhaW5oZ2ZtZmh0dGVuZHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTUxNjMsImV4cCI6MjA2NjU5MTE2M30.tjdCORYqB02G-24IW37OkY84cEoX-7SuyuMFvpKf7v8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);